### ISSUE TITLE
cuBLAS error

### ISSUE THREAD

**Issue by cometyang** [rustformers/llm#347]
When I enable cuBlas feature, it report the following error:
"cuBLAS error 7 at llama-cpp/ggml-cuda.cu:1573"

**Comment by LLukas22** [comment]
OK im currently able to build with CuBlas enabled. Could you provide infos about your OS, Cuda Version and graphics card?

**Comment by cometyang** [comment]
The error message is below:
```
Loaded hyperparameters
ggml ctx size = 0.09 MB

ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090

cuBLAS error 7 at llama-cpp/ggml-cuda.cu:1573
```
I tried to use llama.cpp to load model with cublas enabled, it can run without issue.

**Comment by LLukas22** [comment]
The error seams to be caused by this line: `CUBLAS_CHECK(cublasSetMathMode(g_cublas_handles[id], CUBLAS_TF32_TENSOR_OP_MATH));` with error `error 7` indicating that `CUBLAS_TF32_TENSOR_OP_MATH` is not supported for your CUDA and GPU combination. 

I don't know why you can build llama.cpp without issues but it mabe has something to do with [these lines](https://github.com/ggerganov/llama.cpp/commit/bbca06e26949686d61a5126332680ba3cccf235c#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR253-R259) which configure the machine parameter, we always assume 61 here. 

If you want you could try the cuda/clblast branch which uses a newer version of llama.cpp as its ggml source: https://github.com/rustformers/llm/pull/325

**Comment by cometyang** [comment]
I am not sure it is the reason since I tested on the newest version llama.cpp. 
When I directly use llama.cpp,it has no issue at all:
```
llama_model_load_internal: using CUDA for GPU acceleration
ggml_cuda_set_main_device: using device 0 (NVIDIA GeForce RTX 3090) as main device
llama_model_load_internal: mem required  = 8861.51 MB (+ 1608.00 MB per state)
llama_model_load_internal: allocating batch_size x (640 kB + n_ctx x 160 B) = 360 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 1 repeating layers to GPU
llama_model_load_internal: offloaded 1/43 layers to GPU
llama_model_load_internal: total VRAM used: 531 MB
llama_new_context_with_model: kv self size  =  400.00 MB

system_info: n_threads = 4 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 512, n_batch = 512, n_predict = 128, n_keep = 0


 umer{}, which is the 
library of the C++ programming language. Therefore, any C++ code that uses or requires the header file "<cstdlib>" will not be affected by this change. [end of text]

llama_print_timings:        load time =  1240.77 ms
llama_print_timings:      sample time =    22.33 ms /    45 runs   (    0.50 ms per token,  2014.87 tokens per second)
llama_print_timings: prompt eval time =   404.50 ms /     2 tokens (  202.25 ms per token,     4.94 tokens per second)
llama_print_timings:        eval time = 11194.95 ms /    44 runs   (  254.43 ms per token,     3.93 tokens per second)
llama_print_timings:       total time = 11630.25 ms
```
I even updated the llm's llama.cpp to the newest one. I will do some investigation and see what cause this.

**Comment by LLukas22** [comment]
I tested it again on Ubuntu 22.04 via WSL with an RTX 3090 and CUDA 12.1 and it works as expected. I think its a problem with the CUDA version or some compilation parameter we are missing.

**Comment by cometyang** [comment]
I checked the flag in build.rs for ggml-sys and try to make them the same as below but it still report the same error. I also tried the branch you mentioned, still the same error.:
```
I llama.cpp build info: 
I UNAME_S:  Linux
I UNAME_P:  x86_64
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include
I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include
I LDFLAGS:  -lcublas -lculibos -lcudart -lcublasLt -lpthread -ldl -lrt -L/usr/local/cuda/lib64 -L/opt/cuda/lib64 -L/targets/x86_64-linux/lib
I CC:       cc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
I CXX:      g++ (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0

cc  -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include   -c ggml.c -o ggml.o
g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include -c llama.cpp -o llama.o
g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include -c examples/common.cpp -o common.o
cc -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include   -c -o k_quants.o k_quants.c
nvcc --forward-unknown-to-host-compiler -arch=native -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_DMMV_Y=1 -DK_QUANTS_PER_ITERATION=2 -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include -Wno-pedantic -c ggml-cuda.cu -o ggml-cuda.o
g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include examples/main/main.cpp ggml.o llama.o common.o k_quants.o ggml-cuda.o -o main -lcublas -lculibos -lcudart -lcublasLt -lpthread -ldl -lrt -L/usr/local/cuda/lib64 -L/opt/cuda/lib64 -L/targets/x86_64-linux/lib```

**Comment by LLukas22** [comment]
Could you try building with the newest main branch again? There were some changes in the underlying `ggml` implementation.

**Comment by cometyang** [comment]
Sure, I will try and get back to you once I get the result.

**Comment by cometyang** [comment]
I checkout the new llm code and run the following code:
cargo run --release --features cublas --example vicuna-chat llama orca-mini-13b.ggmlv3.q4_0.bin 
And it reports the following error:
Loaded hyperparameters
ggml ctx size = 0.09 MB

ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6

cuBLAS error 7 at llama-cpp/ggml-cuda.cu:2504

**Comment by LLukas22** [comment]
@cometyang This is a real headscratcher for me. I'm guessing `llama.cpp` still works fine on your machine? I'm probably gonna downgrade my cuda version to 11.8 in my wsl instance and check if i can reproduce the error. Could you by any chance provide which nvidia driver version you are using?

**Comment by cometyang** [comment]
Sure, it also bugs me. My NVIDIA Dirver Version: 520.61.05, CUDA Version: 11.8
